cd resources
git clone https://github.com/ESX-Org/es_extended [essential]/es_extended
git clone https://github.com/ESX-Org/esx_menu_default [esx]/[ui]/esx_menu_default
git clone https://github.com/ESX-Org/esx_menu_dialog [esx]/[ui]/esx_menu_dialog
git clone https://github.com/ESX-Org/esx_menu_list [esx]/[ui]/esx_menu_list
git clone https://github.com/kanersps/essentialmode [essential]/essentialmode
git clone https://github.com/kanersps/es_admin [essential]/es_admin2
git clone https://github.com/ESX-Org/esx_property [esx]/esx_property
git clone https://github.com/ESX-Org/esx_mecanojob [esx]/esx_mecanojob
git clone https://github.com/ESX-Org/esx_bankerjob [esx]/esx_bankerjob
git clone https://github.com/ESX-Org/esx_ambulancejob [esx]/esx_ambulancejob
git clone https://github.com/ESX-Org/esx_atm [esx]/esx_atm
git clone https://github.com/ESX-Org/esx_joblisting [esx]/esx_joblisting
git clone https://github.com/ESX-Org/esx_animations [esx]/esx_animations
git clone https://github.com/ESX-Org/esx_vehicleshop [esx]/esx_vehicleshop
git clone https://github.com/ESX-Org/esx_policejob [esx]/esx_policejob
git clone https://github.com/ESX-Org/esx_billing [esx]/esx_billing
git clone https://github.com/ESX-Org/esx_realestateagentjob [esx]/esx_realestateagentjob
git clone https://github.com/ESX-Org/esx_accessories [esx]/esx_accessories
git clone https://github.com/ESX-Org/esx_weashops.git [esx]/esx_weashops
git clone https://github.com/ESX-Org/esx_drugs [esx]/esx_drugs
git clone https://github.com/ESX-Org/esx_jobs [esx]/esx_jobs
git clone https://github.com/ESX-Org/instance [esx]/instance
git clone https://github.com/ESX-Org/esx_addonaccount [esx]/esx_addonaccount
git clone https://github.com/ESX-Org/esx_addoninventory [esx]/esx_addoninventory
git clone https://github.com/ESX-Org/esx_datastore [esx]/esx_datastore
git clone https://github.com/ESX-Org/esx_skin [esx]/esx_skin
git clone https://github.com/FXServer-ESX/fxserver-esx_status [esx]/esx_status
git clone https://github.com/ESX-Org/esx_menu_list [esx]/esx_menu_list
git clone https://github.com/ESX-Org/esx_shops [esx]/esx_shops
git clone https://github.com/ESX-Org/esx_dmvschool [esx]/esx_dmvschool
git clone https://github.com/ESX-Org/esx_holdup [esx]/esx_holdup
git clone https://github.com/ESX-Org/esx_taxijob [esx]/esx_taxijob
git clone https://github.com/ESX-Org/esx_clotheshop [esx]/esx_clotheshop
git clone https://github.com/ESX-Org/esx_rpchat [esx]/esx_rpchat
git clone https://github.com/ESX-Org/esx_lscustom [esx]/esx_lscustom
git clone https://github.com/ESX-Org/esx_identity [esx]/esx_identity
git clone https://github.com/ESX-Org/skinchanger skinchanger
git clone https://github.com/ESX-Org/esx_boat [esx]/esx_boat
git clone https://github.com/ESX-Org/esx_society [esx]/esx_society
git clone https://github.com/ESX-Org/esx_basicneeds [esx]/esx_basicneeds
git clone https://github.com/FXServer-ESX/fxserver-esx_sit [esx]/esx_sit
git clone https://github.com/ESX-Org/esx_cruisecontrol [esx]/esx_cruisecontrol
git clone https://github.com/FXServer-ESX/fxserver-esx_garage [esx]/esx_garage
git clone https://github.com/ESX-Org/esx_voice [esx]/esx_voice
git clone https://github.com/ESX-Org/esx_service [esx]/esx_service
git clone https://github.com/FXServer-ESX/fxserver-esx_optionalneeds [esx]/esx_optionalneeds
git clone https://github.com/HumanTree92/esx_eden_garage [Hunter]/esx_eden_garage
git clone https://github.com/ESX-Org/esx_license [esx]/esx_license
git clone https://github.com/ESX-Org/esx_boilerplate [esx]/esx_boilerplate
git clone https://github.com/FXServer-ESX/fxserver-esx_barbershop [esx]/esx_barbershop
git clone https://github.com/FXServer-ESX/fxserver-es_camera es_camera
git clone https://github.com/ESX-Org/cron cron
git clone https://github.com/ESX-Org/async async
git clone https://github.com/brouznouf/fivem-mysql-async mysql-async
git clone https://github.com/jonassvensson4/jsfour-register [jsfour]/jsfour-register
